# Generated by Django 4.0.3 on 2022-03-15 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apolloapp', '0002_ticket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in progress'), ('CLOSED', 'closed')], default='closed', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
